# Just wrapper for internal Makefile
.DEFAULT_GOAL:=help

all:
	$(MAKE) -f make-fpga/Makefile $@

build:
	$(MAKE) -f make-fpga/Makefile $@

create:
	$(MAKE) -f make-fpga/Makefile $@

open:
	$(MAKE) -f make-fpga/Makefile $@

save:
	$(MAKE) -f make-fpga/Makefile $@

synth:
	$(MAKE) -f make-fpga/Makefile $@

impl:
	$(MAKE) -f make-fpga/Makefile $@

xsa:
	$(MAKE) -f make-fpga/Makefile $@

bin:
	$(MAKE) -f make-fpga/Makefile $@

clean:
	$(MAKE) -f make-fpga/Makefile $@

template:
	$(MAKE) -f make-fpga/Makefile $@

help:
	$(MAKE) -f make-fpga/Makefile $@

.PHONY: all build create open save synth impl xsa bin clean template help
